// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzc6hwn7BgPnUewAHLetneA4emAvxcA4s',
    appId: '1:517143541019:web:5c4654883a4ef1f5398fbe',
    messagingSenderId: '517143541019',
    projectId: 'refugio-animal-92181',
    authDomain: 'refugio-animal-92181.firebaseapp.com',
    storageBucket: 'refugio-animal-92181.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzdr8dHK95xe6gaZpFSONzfdxnzhxQGs',
    appId: '1:517143541019:android:f98b260c13f5f752398fbe',
    messagingSenderId: '517143541019',
    projectId: 'refugio-animal-92181',
    storageBucket: 'refugio-animal-92181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGZNz0WBNz7T7lgZfA3CzlnciIG3peqDc',
    appId: '1:517143541019:ios:075662f88f397a3e398fbe',
    messagingSenderId: '517143541019',
    projectId: 'refugio-animal-92181',
    storageBucket: 'refugio-animal-92181.appspot.com',
    iosBundleId: 'com.example.refugioAnimales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGZNz0WBNz7T7lgZfA3CzlnciIG3peqDc',
    appId: '1:517143541019:ios:075662f88f397a3e398fbe',
    messagingSenderId: '517143541019',
    projectId: 'refugio-animal-92181',
    storageBucket: 'refugio-animal-92181.appspot.com',
    iosBundleId: 'com.example.refugioAnimales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzc6hwn7BgPnUewAHLetneA4emAvxcA4s',
    appId: '1:517143541019:web:cc7022b3409c2c23398fbe',
    messagingSenderId: '517143541019',
    projectId: 'refugio-animal-92181',
    authDomain: 'refugio-animal-92181.firebaseapp.com',
    storageBucket: 'refugio-animal-92181.appspot.com',
  );
}
